[package]
name = "vpn-wrapper"
version = "0.1.0"
authors = ["Jason Stelzer <jasonstelzer@boomi.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
exec = "0.3.1"
nix = "0.17.0"
